### ISSUE TITLE
关于第三章一键训练模型的一些问题。

### ISSUE THREAD

**Issue by HBULXY1997** [dlod-openvino/book#1]
老师您好，感谢您百忙之中查看此问题。
在学习完书中第三章一键训练模型后，我成功的实现了一键训练猫狗识别的程序。于是我尝试着使用我自己的训练集，按照您的方法对图片进行标注以及训练模型。我成功的完成了模型的训练，也保存了冻结图文件，但是当我运行object_detection_example_2文件，即想看模型对于测试集的训练效果时，运行程序时命令行窗口显示如下错误。Traceback (most recent call last):
  File "object_detection_example_2.py", line 11, in <module>
    from utils import label_map_util
  File "D:\tf_train\models\research\object_detection\utils\label_map_util.py", line 21, in <module>
    from object_detection.protos import string_int_label_map_pb2
  File "D:\tf_train\workspaces\weights_training_dome1\object_detection.py", line 12, in <module>
    from utils import visualization_utils as vis_util
  File "D:\tf_train\models\research\object_detection\utils\visualization_utils.py", line 36, in <module>
    from object_detection.core import standard_fields as fields
ModuleNotFoundError: No module named 'object_detection.core'; 'object_detection' is not a package

我尝试了网上参考的解决方法，但是没有找到问题的原因。
后来我多次反复在控制台输入 python object_detection_example_2.py又成功执行了test图片的预测。我也不知道为什么会发生这样的事情，希望老师可以指点我一下。

**Comment by dlod-openvino** [comment]
麻烦加我微信，我拉你进入微信支持群，微信号：PCI-GPIB

ModuleNotFoundError: 大概率是Python模块查找路径没有配置好，参考P49页



dlod_openvino@163.com
 
发件人： HBULXY1997
发送时间： 2020-05-01 15:09
收件人： dlod-openvino/book
抄送： Subscribed
主题： [dlod-openvino/book] 关于第三章一键训练模型的一些问题。 (#1)
老师您好，感谢您百忙之中查看此问题。
在学习完书中第三章一键训练模型后，我成功的实现了一键训练猫狗识别的程序。于是我尝试着使用我自己的训练集，按照您的方法对图片进行标注以及训练模型。我成功的完成了模型的训练，也保存了冻结图文件，但是当我运行object_detection_example_2文件，即想看模型对于测试集的训练效果时，运行程序时命令行窗口显示如下错误。Traceback (most recent call last):
File "object_detection_example_2.py", line 11, in 
from utils import label_map_util
File "D:\tf_train\models\research\object_detection\utils\label_map_util.py", line 21, in 
from object_detection.protos import string_int_label_map_pb2
File "D:\tf_train\workspaces\weights_training_dome1\object_detection.py", line 12, in 
from utils import visualization_utils as vis_util
File "D:\tf_train\models\research\object_detection\utils\visualization_utils.py", line 36, in 
from object_detection.core import standard_fields as fields
ModuleNotFoundError: No module named 'object_detection.core'; 'object_detection' is not a package
我尝试了网上参考的解决方法，但是没有找到问题的原因。
后来我多次反复在控制台输入 python object_detection_example_2.py又成功执行了test图片的预测。我也不知道为什么会发生这样的事情，希望老师可以指点我一下。
―
